---
elasticsearch:
  image: elasticsearch:2
  ports:
    - "9200:9200"

kibana:
  image: kibana:4
  ports:
    - "5601:5601"
  links:
    - "elasticsearch:elasticsearch"

logstash:
  command: logstash -f /conf/logstash.conf
  image: logstash:2
  volumes:
    - "./conf:/conf"
  links:
    - "elasticsearch:elasticsearch"

webserver:
  build: fake-webserver
  hostname: fake-webserver
  links:
    - "logstash:logstash"
